"""Edit Profile

Revision ID: 237e33196d3b
Revises: 692cb862953f
Create Date: 2025-11-27 00:28:29.253031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237e33196d3b'
down_revision = '692cb862953f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_edit_profile', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_edit_profile')

    # ### end Alembic commands ###
