"""Unique Unit per Resident

Revision ID: 692cb862953f
Revises: a76a657e987d
Create Date: 2025-11-25 13:57:41.033156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692cb862953f'
down_revision = 'a76a657e987d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_persondetails_building_floor_apartment'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_details', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_persondetails_building_floor_apartment'), ['building', 'floor', 'apartment'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
