"""Bus Reservation

Revision ID: 734a3f88d6d4
Revises: 28dabdae558b
Create Date: 2025-12-28 08:42:51.293479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734a3f88d6d4'
down_revision = '28dabdae558b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_transport_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('election_transport_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_transport_bookings_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election_transport_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_transport_bookings_phone'))

    op.drop_table('election_transport_bookings')
    # ### end Alembic commands ###
