"""add phone to person_details

Revision ID: 7712b5fa2902
Revises: 95b90268e93c
Create Date: 2025-11-15 16:53:49.095879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7712b5fa2902'
down_revision = '95b90268e93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_details', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
