"""add person_details table

Revision ID: 941bb7ea091d
Revises: 5a1f22d7244b
Create Date: 2025-11-13 21:44:37.985765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941bb7ea091d'
down_revision = '5a1f22d7244b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('building', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=False),
    sa.Column('apartment', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_details')
    # ### end Alembic commands ###
