"""Create Admin Building

Revision ID: 9d645aa5612d
Revises: 83ae784c9121
Create Date: 2025-11-25 12:27:20.231112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d645aa5612d'
down_revision = '83ae784c9121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_buildings_admin_id'), ['admin_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_buildings_admin_id'))

    op.drop_table('admin_buildings')
    # ### end Alembic commands ###
