"""Unique Unit

Revision ID: a76a657e987d
Revises: 9d645aa5612d
Create Date: 2025-11-25 13:27:24.378237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76a657e987d'
down_revision = '9d645aa5612d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_details', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_persondetails_building_floor_apartment', ['building', 'floor', 'apartment'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_details', schema=None) as batch_op:
        batch_op.drop_constraint('uq_persondetails_building_floor_apartment', type_='unique')

    # ### end Alembic commands ###
